language: java

addons:
  apt:
    packages:
      - oracle-java9-installer
matrix:
  include:
	jdk: oraclejdk9

before_script:
- cd OpenRobertaUSB

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  irc: "chat.freenode.net#open-roberta"
